---
- name: UnRegister the subscription
  community.general.redhat_subscription:
    username: "{{ red_hat_account }}"
    password: "{{ red_hat_account_password }}"  # noqa no-log-password
    force_register: true
    state: absent
  delegate_to: "{{ item.1.ip }}"
  async: 300
  poll: 0
  register: register_subscription_result
  loop: "{{ target_vm_info | subelements('networks') }}"
  when:
    - item.0.guest_fullname | regex_search("^Red Hat")

- name: Make sure the tasks are until completion
  ansible.builtin.async_status:
    jid: "{{ item.0.ansible_job_id }}"
  delegate_to: "{{ item.1.ip }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 3
  loop: "{{ target_vm_info | subelements('networks') }}"
  when:
    - item.0.guest_fullname | regex_search("^Red Hat")
